apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.1
  nodeSets:
    - name: default
      count: 3 # Update the count to scale up to 3 nodes
      config:
        node.store.allow_mmap: false
