version: "3.8"

services:
  # Pyroscope Server
  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope-server
    ports:
      - "4040:4040"
    command:
      - "server"
    environment:
      - PYROSCOPE_LOG_LEVEL=info
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    networks:
      - profiling

  # Your Go Application
  go-app:
    build: .
    container_name: go-demo-app
    ports:
      - "8080:8080"
      - "6060:6060" # pprof endpoint
    environment:
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
      - PORT=8080
    depends_on:
      - pyroscope
    networks:
      - profiling

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - profiling

volumes:
  pyroscope-data:
  grafana-data:

networks:
  profiling:
    driver: bridge
